version: "3.9"

services:
  db:
    image: postgres:9.6
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  phoenix:
    build: ./phoenix
    volumes:
      - ./phoenix:/app
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: ./react
    command: npm start
    volumes:
      - ./react:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:
